services:
  schedule-postgres:
    image: postgres:15-alpine
    container_name: schedule-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - schedule_postgres_data:/var/lib/postgresql/data
    networks:
      - schedule-postgres-net

  schedule-bot:
    build: ./bot
    container_name: schedule-bot
    restart: unless-stopped
    depends_on:
      - schedule-postgres
      - schedule-redis
    environment:
      DB_HOST: schedule-postgres
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      TOKEN: ${TOKEN}
      PROXY: ${PROXY}
      VLESS_PROXY: ${VLESS_PROXY}
      REDIS_HOST: schedule-redis
      REDIS_PORT: 6379
    volumes:
      - ./bot:/app
    networks:
      - schedule-postgres-net
      - schedule-redis-net

  schedule-redis:
    image: redis:7
    container_name: schedule-redis
    restart: unless-stopped
    networks:
      - schedule-redis-net

networks:
  schedule-postgres-net:
    driver: bridge
  schedule-redis-net:
    driver: bridge

volumes:
  schedule_postgres_data:
    name: schedule-postgres-data