FROM python:3.14

WORKDIR /app

RUN pip install poetry

COPY pyproject.toml poetry.lock /app/
RUN poetry config virtualenvs.create false
RUN poetry install --no-root

COPY src/bot /app/src/bot

ENV PYTHONPATH=/app/src
CMD ["python", "-m", "bot"]
