BOT_PHOTO_PATH = "./img/bot.png"
LOGS_PATH = "./logs/"
MINUTES_TO_RESET_SCHEDULE_CACHE = 60
MINUTES_TO_CHECK_CHANGES = 60
GET_SCHEDULE_TIMEOUT = 10
GET_MAIN_PAGE_TIMEOUT = 20
GET_CHANGES_FILE_TIMEOUT = 20
