"""empty message

Revision ID: 3b0db305b1fc
Revises: ae1be184f287
Create Date: 2026-03-25 14:02:53.587992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b0db305b1fc'
down_revision: Union[str, Sequence[str], None] = 'ae1be184f287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'grade',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'grade',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
